"""empty message

Revision ID: 00f83a4d640f
Revises: e6fcfceb0be3
Create Date: 2021-11-29 16:20:24.124558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f83a4d640f'
down_revision = 'e6fcfceb0be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_resumes_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_resumes_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
