"""empty message

Revision ID: 2091f422f0d0
Revises: 1a99f8c3f3ab
Create Date: 2021-11-27 23:05:12.790845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2091f422f0d0'
down_revision = '1a99f8c3f3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_number', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_professors_role_id'), ['role_id'], unique=False)
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('leader_student')
        batch_op.drop_column('name')
        batch_op.drop_column('teacher')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('college')

    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('leader_student', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_professors_role_id'))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('role_id')
        batch_op.drop_column('id_number')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
