"""empty message

Revision ID: 2bc42f9cea51
Revises: 305170054e0e
Create Date: 2021-11-29 00:01:01.780807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc42f9cea51'
down_revision = '305170054e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # ### end Alembic commands ###
