"""empty message

Revision ID: 305170054e0e
Revises: 7d82debcdbd5
Create Date: 2021-11-28 23:43:32.924039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305170054e0e'
down_revision = '7d82debcdbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('certification_name', sa.String(length=256), nullable=True),
    sa.Column('certification_path', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certifications')
    # ### end Alembic commands ###
