"""empty message

Revision ID: 7d82debcdbd5
Revises: 4aebfc3edc17
Create Date: 2021-11-28 23:42:08.533822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d82debcdbd5'
down_revision = '4aebfc3edc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('certification_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('certification_path', sa.VARCHAR(length=256), nullable=True),
    sa.CheckConstraint('confirmed IN (0, 1)'),
    sa.PrimaryKeyConstraint('id', 'teacher_id')
    )
    # ### end Alembic commands ###
