"""empty message

Revision ID: 867d1e1f9322
Revises: 8837868145bb
Create Date: 2021-11-27 22:28:19.938722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867d1e1f9322'
down_revision = '8837868145bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('teacher', sa.String(length=128), nullable=True),
    sa.Column('leader_student', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=128), nullable=True),
    sa.Column('college', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('organizations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('teacher', sa.VARCHAR(length=128), nullable=True),
    sa.Column('leader_student', sa.VARCHAR(length=128), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=128), nullable=True),
    sa.Column('college', sa.VARCHAR(length=256), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.CheckConstraint('confirmed IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('professors')
    # ### end Alembic commands ###
