"""empty message

Revision ID: de544a00327f
Revises: 42022eeb3fae
Create Date: 2021-11-28 23:06:31.686464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de544a00327f'
down_revision = '42022eeb3fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('certification_name', sa.String(length=256), nullable=True),
    sa.Column('certification_path', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', 'teacher_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certifications')
    # ### end Alembic commands ###
