"""empty message

Revision ID: e6fcfceb0be3
Revises: ebd5ec213a20
Create Date: 2021-11-29 16:12:03.752148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fcfceb0be3'
down_revision = 'ebd5ec213a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index('ix_resumes_recruitment_id')
        batch_op.drop_index('ix_resumes_student_id')
        batch_op.drop_column('student_id')
        batch_op.drop_column('recruitment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruitment_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_resumes_student_id', ['student_id'], unique=False)
        batch_op.create_index('ix_resumes_recruitment_id', ['recruitment_id'], unique=False)

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
