"""empty message

Revision ID: ebd5ec213a20
Revises: 5a85b8686edc
Create Date: 2021-11-29 16:09:31.792008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd5ec213a20'
down_revision = '5a85b8686edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruitment_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_resumes_recruitment')
        batch_op.create_index(batch_op.f('ix_resumes_recruitment_id'), ['recruitment_id'], unique=False)
        batch_op.drop_column('recruitment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruitment', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_resumes_recruitment_id'))
        batch_op.create_index('ix_resumes_recruitment', ['recruitment'], unique=False)
        batch_op.drop_column('recruitment_id')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
